### ISSUE TITLE
Deployed application randomly throws 500 error on homepage

### ISSUE THREAD

**Issue by BeardedFish** [DarianBenam/Domain-Status-Report#4]
Service Log:

```
● domain-status-report.service - Domain Status Report
     Loaded: loaded (/etc/systemd/system/domain-status-report.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2023-10-28 03:03:53 EDT; 3 weeks 0 days ago
   Main PID: 295308 (dotnet)
      Tasks: 18 (limit: 2234)
     Memory: 174.7M
        CPU: 12min 1.772s
     CGroup: /system.slice/domain-status-report.service
             └─295308 /usr/bin/dotnet /var/www/Domain-Status-Report/bin/Release/net6.0/publish/DomainStatusReport.dll

Nov 18 21:13:31 dbenam-ubuntu dotnet-domain-status-report[295308]: fail: Microsoft.AspNetCore.Server.Kestrel[13]
Nov 18 21:13:31 dbenam-ubuntu dotnet-domain-status-report[295308]:       Connection id "0HMUNIHEM5T40", Request id "0HMUNIHEM5T40:00000002": An unhandled exception was thrown by the application.
Nov 18 21:13:31 dbenam-ubuntu dotnet-domain-status-report[295308]:       System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Diagnostics.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
Nov 18 21:13:31 dbenam-ubuntu dotnet-domain-status-report[295308]:       
Nov 18 21:13:31 dbenam-ubuntu dotnet-domain-status-report[295308]:       File name: 'Microsoft.AspNetCore.Diagnostics.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
Nov 18 21:13:31 dbenam-ubuntu dotnet-domain-status-report[295308]:          at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
Nov 18 21:13:31 dbenam-ubuntu dotnet-domain-status-report[295308]:          at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
Nov 18 21:13:31 dbenam-ubuntu dotnet-domain-status-report[295308]:          at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
Nov 18 21:13:31 dbenam-ubuntu dotnet-domain-status-report[295308]:          at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
Nov 18 21:13:31 dbenam-ubuntu dotnet-domain-status-report[295308]:          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by BeardedFish** [comment]
Been a year since I logged this and I haven't experienced this issue since. Closing issue.
